# Analytics Service Deployment
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: analytics-service-build
  labels:
    app: analytics-service
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: analytics-service:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  lookupPolicy:
    local: false
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  selector:
    deploymentconfig: analytics-service
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    deploymentconfig: analytics-service
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: analytics-service
        deploymentconfig: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: analytics-service:latest
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: PORT
              value: "8082"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database-name
            - name: RABBITMQ_URL
              value: "amqp://admin:rabbitmq_pass@rabbitmq-service:5672"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - analytics-service
        from:
          kind: ImageStreamTag
          name: analytics-service:latest
