# ============================================
# Frontend UI Deployment
# ============================================
# This file contains all Kubernetes/OpenShift resources for Frontend

---
# BuildConfig - Builds Docker image from source
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend-build
  labels:
    app: notes-app
    tier: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []

---
# ImageStream - Stores built Docker images
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  labels:
    app: notes-app
    tier: frontend
spec:
  lookupPolicy:
    local: true

---
# ConfigMap - Frontend configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: notes-app
    tier: frontend
data:
  REACT_APP_API_URL: "https://backend-route-houssemsouari-dev.apps.rm2.thpm.p1.openshiftapps.com"

---
# DeploymentConfig - Frontend pod configuration
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: frontend
  labels:
    app: notes-app
    tier: frontend
spec:
  replicas: 2  # Two frontend pods for scalability
  selector:
    app: notes-app
    tier: frontend
    deploymentconfig: frontend
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: notes-app
        tier: frontend
        deploymentconfig: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Always
          
          # Environment variables
          env:
            - name: PORT
              value: "3000"
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_API_URL
          
          ports:
            - containerPort: 3000
              protocol: TCP
          
          # Resource limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          
          # Readiness probe
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
  
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - frontend
        from:
          kind: ImageStreamTag
          name: frontend:latest

---
# Service - Internal load balancer for frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: notes-app
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: notes-app
    tier: frontend
    deploymentconfig: frontend

---
# Route - Exposes application to the internet
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
  labels:
    app: notes-app
    tier: frontend
spec:
  to:
    kind: Service
    name: frontend-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge  # HTTPS termination at router
    insecureEdgeTerminationPolicy: Redirect  # Force HTTPS
  wildcardPolicy: None
